#!/bin/sh
#
#  Splash logo to framebuffer
#

start() {
    printf "Splash logo to framebuffer: "
    /usr/bin/fblogo /boot/splash.bmp
    echo "OK"
}

stop() {
        printf "Splash stop unsupported: "
        echo "OK"
}

case "$1" in
  start)
        start
        ;;
  stop)
        stop
        ;;
  restart|reload)
        stop
        start
        ;;
  *)
        echo "Usage: $0 {start|stop|restart}"
        exit 1
esac

exit $?
